services:
#  api:
#    build: .
#    container_name: cafeteria-api
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_database:5432/${POSTGRES_DB}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    depends_on:
#      postgres:
#        condition: service_healthy
  postgres:
    image: postgres:latest
    container_name: cafeteria_database
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      timeout: 5s
      interval: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - cafeteria-net

networks:
  cafeteria-net:
    driver: bridge

volumes:
  pgdata: